language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
script: ./mvnw clean install

jobs:
    include:
        - stage: Test
          script: ./mvnw clean test  

notifications:
        email: frankshe@hotmail.com
        
